//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditWarehouseLocationsDetail
    {
        public int AuditDetailID { get; set; }
        public int AuditID { get; set; }
        public int CompanyID { get; set; }
        public int BinID { get; set; }
        public string ProductSKU { get; set; }
        public int QuantityStock { get; set; }
        public int QuantityAudit { get; set; }
        public int QuantityDifference { get; set; }
        public int Action { get; set; }
        public Nullable<int> BinMovementID { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        public virtual AuditWarehouseLocation AuditWarehouseLocation { get; set; }
        public virtual Bin Bin { get; set; }
        public virtual Company Company { get; set; }
    }
}
