//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bin()
        {
            this.AuditWarehouseLocationsDetails = new HashSet<AuditWarehouseLocationsDetail>();
            this.BinContents = new HashSet<BinContent>();
        }
    
        public int BinID { get; set; }
        public string BinCode { get; set; }
        public int BinTypeID { get; set; }
        public int LocationID { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditWarehouseLocationsDetail> AuditWarehouseLocationsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinContent> BinContents { get; set; }
        public virtual BinType BinType { get; set; }
        public virtual WarehouseLocation WarehouseLocation { get; set; }
    }
}
