//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinContent
    {
        public int BinContentID { get; set; }
        public int CompanyID { get; set; }
        public int BinID { get; set; }
        public string ProductSKU { get; set; }
        public string SerialNumber { get; set; }
        public int Qty { get; set; }
    
        public virtual Bin Bin { get; set; }
        public virtual Company Company { get; set; }
        public virtual CompanyProductSKU CompanyProductSKU { get; set; }
    }
}
