//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinMovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinMovement()
        {
            this.BulkMovementsDetails = new HashSet<BulkMovementsDetail>();
        }
    
        public int BinMovementID { get; set; }
        public int BinMovementTypeID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> FromBinID { get; set; }
        public Nullable<int> ToBinID { get; set; }
        public string ProductSKU { get; set; }
        public int Qty { get; set; }
        public string Comments { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime MovementDate { get; set; }
        public string MovementBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkMovementsDetail> BulkMovementsDetails { get; set; }
        public virtual Company Company { get; set; }
        public virtual CompanyProductSKU CompanyProductSKU { get; set; }
    }
}
