//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandAlia
    {
        public int BrandAlias { get; set; }
        public int BrandID { get; set; }
        public string Alias { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
