//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkMovementsDetail
    {
        public int BulkMovementsID { get; set; }
        public int BinMovementsID { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual BinMovement BinMovement { get; set; }
        public virtual BulkMovement BulkMovement { get; set; }
    }
}
