//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkMatch
    {
        public int BulkMatchID { get; set; }
        public string BulkID { get; set; }
        public string BulkLPN { get; set; }
        public int Company { get; set; }
        public int LocationID { get; set; }
        public int BinID { get; set; }
        public string BinCode { get; set; }
        public string ProductSKU { get; set; }
        public int Qty { get; set; }
        public Nullable<int> Status { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
