//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartOrder_Details
    {
        public int id { get; set; }
        public int PalletID { get; set; }
        public int OrderNumber { get; set; }
        public int BinId { get; set; }
        public string SKU { get; set; }
        public string SerialNumber { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<int> Size { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> UnitRetail { get; set; }
    }
}
