//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.SKUDatas = new HashSet<SKUData>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Attribute01Name { get; set; }
        public string Attribute02Name { get; set; }
        public string Attribute03Name { get; set; }
        public string Attribute04Name { get; set; }
        public string Attribute05Name { get; set; }
        public string Attribute06Name { get; set; }
        public string Attribute07Name { get; set; }
        public string Attribute08Name { get; set; }
        public string Attribute09Name { get; set; }
        public string Attribute10Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUData> SKUDatas { get; set; }
    }
}
