//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTier
    {
        public int CategoryTierID { get; set; }
        public int CategoryID { get; set; }
        public int TierID { get; set; }
        public int Size { get; set; }
        public decimal FloorPrice { get; set; }
        public decimal Frieght { get; set; }
        public decimal DocOverhead { get; set; }
        public decimal eComShipping { get; set; }
        public decimal Other { get; set; }
    }
}
