//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAssemblyDetail
    {
        public string ProductSKU { get; set; }
        public string SubProductSKU { get; set; }
        public int CompanyID { get; set; }
        public int SubProductSKUQtyRequired { get; set; }
        public bool isRequired { get; set; }
        public bool AssemblyRequired { get; set; }
        public System.DateTime EnteredDate { get; set; }
    }
}
