//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCategoryBrandModel
    {
        public int CCBMID { get; set; }
        public int CompanyID { get; set; }
        public int CategoryID { get; set; }
        public int BrandID { get; set; }
        public int ModelID { get; set; }
    }
}
