//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concept
    {
        public int ConceptID { get; set; }
        public string Type { get; set; }
        public int CountryID { get; set; }
        public bool Apply_IGI { get; set; }
        public bool Apply_IVA { get; set; }
        public bool Apply_eComMarketplaceFee { get; set; }
        public string LastUpdateUser { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
