//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerMessage()
        {
            this.CustomerMessagesInternalNotes = new HashSet<CustomerMessagesInternalNote>();
            this.CustomerMessagesMovements = new HashSet<CustomerMessagesMovement>();
        }
    
        public int Id { get; set; }
        public string LicencePlateNumber { get; set; }
        public Nullable<int> PurchaseSites_Id { get; set; }
        public string CustomerNames { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerEmail { get; set; }
        public string OrderNumber { get; set; }
        public string CustomerMessage1 { get; set; }
        public string FileAttachedURL { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> Assignmentdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMessagesInternalNote> CustomerMessagesInternalNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMessagesMovement> CustomerMessagesMovements { get; set; }
        public virtual PurchaseSite PurchaseSite { get; set; }
    }
}
