//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchageRateHistory
    {
        public int ExchageRateHistoryID { get; set; }
        public int ExchageRateID { get; set; }
        public string Currency { get; set; }
        public decimal Rate { get; set; }
        public Nullable<bool> isFirst { get; set; }
        public string Comment { get; set; }
        public string LastUpdateUser { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
