//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange_rate
    {
        public int Id { get; set; }
        public Nullable<decimal> AED { get; set; }
        public Nullable<decimal> AFN { get; set; }
        public Nullable<decimal> ALL { get; set; }
        public Nullable<decimal> AMD { get; set; }
        public Nullable<decimal> ANG { get; set; }
        public Nullable<decimal> AOA { get; set; }
        public Nullable<decimal> ARS { get; set; }
        public Nullable<decimal> AUD { get; set; }
        public Nullable<decimal> AWG { get; set; }
        public Nullable<decimal> AZN { get; set; }
        public Nullable<decimal> BAM { get; set; }
        public Nullable<decimal> BBD { get; set; }
        public Nullable<decimal> BDT { get; set; }
        public Nullable<decimal> BGN { get; set; }
        public Nullable<decimal> BHD { get; set; }
        public Nullable<decimal> BIF { get; set; }
        public Nullable<decimal> BMD { get; set; }
        public Nullable<decimal> BND { get; set; }
        public Nullable<decimal> BOB { get; set; }
        public Nullable<decimal> BRL { get; set; }
        public Nullable<decimal> BSD { get; set; }
        public Nullable<decimal> BTC { get; set; }
        public Nullable<decimal> BTN { get; set; }
        public Nullable<decimal> BWP { get; set; }
        public Nullable<decimal> BYN { get; set; }
        public Nullable<decimal> BYR { get; set; }
        public Nullable<decimal> BZD { get; set; }
        public Nullable<decimal> CAD { get; set; }
        public Nullable<decimal> CDF { get; set; }
        public Nullable<decimal> CHF { get; set; }
        public Nullable<decimal> CLF { get; set; }
        public Nullable<decimal> CLP { get; set; }
        public Nullable<decimal> CNY { get; set; }
        public Nullable<decimal> COP { get; set; }
        public Nullable<decimal> CRC { get; set; }
        public Nullable<decimal> CUC { get; set; }
        public Nullable<decimal> CUP { get; set; }
        public Nullable<decimal> CVE { get; set; }
        public Nullable<decimal> CZK { get; set; }
        public Nullable<decimal> DJF { get; set; }
        public Nullable<decimal> DKK { get; set; }
        public Nullable<decimal> DOP { get; set; }
        public Nullable<decimal> DZD { get; set; }
        public Nullable<decimal> EGP { get; set; }
        public Nullable<decimal> ERN { get; set; }
        public Nullable<decimal> ETB { get; set; }
        public Nullable<decimal> EUR { get; set; }
        public Nullable<decimal> FJD { get; set; }
        public Nullable<decimal> FKP { get; set; }
        public Nullable<decimal> GBP { get; set; }
        public Nullable<decimal> GEL { get; set; }
        public Nullable<decimal> GGP { get; set; }
        public Nullable<decimal> GHS { get; set; }
        public Nullable<decimal> GIP { get; set; }
        public Nullable<decimal> GMD { get; set; }
        public Nullable<decimal> GNF { get; set; }
        public Nullable<decimal> GTQ { get; set; }
        public Nullable<decimal> GYD { get; set; }
        public Nullable<decimal> HKD { get; set; }
        public Nullable<decimal> HNL { get; set; }
        public Nullable<decimal> HRK { get; set; }
        public Nullable<decimal> HTG { get; set; }
        public Nullable<decimal> HUF { get; set; }
        public Nullable<decimal> IDR { get; set; }
        public Nullable<decimal> ILS { get; set; }
        public Nullable<decimal> IMP { get; set; }
        public Nullable<decimal> INR { get; set; }
        public Nullable<decimal> IQD { get; set; }
        public Nullable<decimal> IRR { get; set; }
        public Nullable<decimal> ISK { get; set; }
        public Nullable<decimal> JEP { get; set; }
        public Nullable<decimal> JMD { get; set; }
        public Nullable<decimal> JOD { get; set; }
        public Nullable<decimal> JPY { get; set; }
        public Nullable<decimal> KES { get; set; }
        public Nullable<decimal> KGS { get; set; }
        public Nullable<decimal> KHR { get; set; }
        public Nullable<decimal> KMF { get; set; }
        public Nullable<decimal> KPW { get; set; }
        public Nullable<decimal> KRW { get; set; }
        public Nullable<decimal> KWD { get; set; }
        public Nullable<decimal> KYD { get; set; }
        public Nullable<decimal> KZT { get; set; }
        public Nullable<decimal> LAK { get; set; }
        public Nullable<decimal> LBP { get; set; }
        public Nullable<decimal> LKR { get; set; }
        public Nullable<decimal> LRD { get; set; }
        public Nullable<decimal> LSL { get; set; }
        public Nullable<decimal> LTL { get; set; }
        public Nullable<decimal> LVL { get; set; }
        public Nullable<decimal> LYD { get; set; }
        public Nullable<decimal> MAD { get; set; }
        public Nullable<decimal> MDL { get; set; }
        public Nullable<decimal> MGA { get; set; }
        public Nullable<decimal> MKD { get; set; }
        public Nullable<decimal> MMK { get; set; }
        public Nullable<decimal> MNT { get; set; }
        public Nullable<decimal> MOP { get; set; }
        public Nullable<decimal> MRO { get; set; }
        public Nullable<decimal> MUR { get; set; }
        public Nullable<decimal> MVR { get; set; }
        public Nullable<decimal> MWK { get; set; }
        public Nullable<decimal> MXN { get; set; }
        public Nullable<decimal> MYR { get; set; }
        public Nullable<decimal> MZN { get; set; }
        public Nullable<decimal> NAD { get; set; }
        public Nullable<decimal> NGN { get; set; }
        public Nullable<decimal> NIO { get; set; }
        public Nullable<decimal> NOK { get; set; }
        public Nullable<decimal> NPR { get; set; }
        public Nullable<decimal> NZD { get; set; }
        public Nullable<decimal> OMR { get; set; }
        public Nullable<decimal> PAB { get; set; }
        public Nullable<decimal> PEN { get; set; }
        public Nullable<decimal> PGK { get; set; }
        public Nullable<decimal> PHP { get; set; }
        public Nullable<decimal> PKR { get; set; }
        public Nullable<decimal> PLN { get; set; }
        public Nullable<decimal> PYG { get; set; }
        public Nullable<decimal> QAR { get; set; }
        public Nullable<decimal> RON { get; set; }
        public Nullable<decimal> RSD { get; set; }
        public Nullable<decimal> RUB { get; set; }
        public Nullable<decimal> RWF { get; set; }
        public Nullable<decimal> SAR { get; set; }
        public Nullable<decimal> SBD { get; set; }
        public Nullable<decimal> SCR { get; set; }
        public Nullable<decimal> SDG { get; set; }
        public Nullable<decimal> SEK { get; set; }
        public Nullable<decimal> SGD { get; set; }
        public Nullable<decimal> SHP { get; set; }
        public Nullable<decimal> SLL { get; set; }
        public Nullable<decimal> SOS { get; set; }
        public Nullable<decimal> SRD { get; set; }
        public Nullable<decimal> STD { get; set; }
        public Nullable<decimal> SVC { get; set; }
        public Nullable<decimal> SYP { get; set; }
        public Nullable<decimal> SZL { get; set; }
        public Nullable<decimal> THB { get; set; }
        public Nullable<decimal> TJS { get; set; }
        public Nullable<decimal> TMT { get; set; }
        public Nullable<decimal> TND { get; set; }
        public Nullable<decimal> TOP { get; set; }
        public Nullable<decimal> TRY { get; set; }
        public Nullable<decimal> TTD { get; set; }
        public Nullable<decimal> TWD { get; set; }
        public Nullable<decimal> TZS { get; set; }
        public Nullable<decimal> UAH { get; set; }
        public Nullable<decimal> UGX { get; set; }
        public Nullable<decimal> USD { get; set; }
        public Nullable<decimal> UYU { get; set; }
        public Nullable<decimal> UZS { get; set; }
        public Nullable<decimal> VEF { get; set; }
        public Nullable<decimal> VND { get; set; }
        public Nullable<decimal> VUV { get; set; }
        public Nullable<decimal> WST { get; set; }
        public Nullable<decimal> XAF { get; set; }
        public Nullable<decimal> XAG { get; set; }
        public Nullable<decimal> XAU { get; set; }
        public Nullable<decimal> XCD { get; set; }
        public Nullable<decimal> XDR { get; set; }
        public Nullable<decimal> XOF { get; set; }
        public Nullable<decimal> XPF { get; set; }
        public Nullable<decimal> YER { get; set; }
        public Nullable<decimal> ZAR { get; set; }
        public Nullable<decimal> ZMK { get; set; }
        public Nullable<decimal> ZMW { get; set; }
        public Nullable<decimal> ZWL { get; set; }
        public System.DateTime ChangeDate { get; set; }
    }
}
