//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalTransfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GlobalTransfer()
        {
            this.GlobalTransferDetails = new HashSet<GlobalTransferDetail>();
            this.GlobalTransferHistories = new HashSet<GlobalTransferHistory>();
            this.GlobalTransferMovements = new HashSet<GlobalTransferMovement>();
        }
    
        public int GlobalTransferID { get; set; }
        public int FromCompnayID { get; set; }
        public int ToCompanyID { get; set; }
        public bool IsPrinted { get; set; }
        public byte StatusID { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlobalTransferDetail> GlobalTransferDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlobalTransferHistory> GlobalTransferHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlobalTransferMovement> GlobalTransferMovements { get; set; }
        public virtual GlobalTransferStatu GlobalTransferStatu { get; set; }
    }
}
