//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalTransferDetail
    {
        public int GlobalTransferDetailID { get; set; }
        public int GlobalTransferID { get; set; }
        public int FromCompanyID { get; set; }
        public string ProductSKU { get; set; }
        public int Quantity { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        public virtual GlobalTransfer GlobalTransfer { get; set; }
    }
}
