//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalSKUConditionHistory
    {
        public int GlobalSKUConditionHistoryID { get; set; }
        public string SKU { get; set; }
        public int Qty { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
