//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryNumber
    {
        public int InventoryID { get; set; }
        public int CompanyID { get; set; }
        public string SKU { get; set; }
        public string MerchantSKU { get; set; }
        public string ASIN { get; set; }
        public int Sequent { get; set; }
        public string InventoryNumber1 { get; set; }
        public bool isActive { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
