//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPageHit
    {
        public System.Guid HitID { get; set; }
        public System.Guid LogSessionID { get; set; }
        public int CompanyID { get; set; }
        public int PageID { get; set; }
        public System.DateTime HitDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual LogSession LogSession { get; set; }
        public virtual Page Page { get; set; }
    }
}
