//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketplace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marketplace()
        {
            this.MarketplaceManagements = new HashSet<MarketplaceManagement>();
        }
    
        public int MarketplaceID { get; set; }
        public string MarketplaceName { get; set; }
        public string MarketplaceAccountName { get; set; }
        public string CountryCode { get; set; }
        public string CurrencyCode { get; set; }
        public string DisplayName { get; set; }
        public string MerchantToken { get; set; }
        public string APIAccessKey { get; set; }
        public string APISecretKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketplaceManagement> MarketplaceManagements { get; set; }
    }
}
