//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketplaceManagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarketplaceManagement()
        {
            //this.MarketPlaceAttributes = new HashSet<MarketPlaceAttribute>();
            this.MarketplaceCompatibleSKUs = new HashSet<MarketplaceCompatibleSKU>();
            this.MarketplaceListingDetails = new HashSet<MarketplaceListingDetail>();
            this.MarketplacePrices = new HashSet<MarketplacePrice>();
        }
    
        public int MarketplaceItemID { get; set; }
        public int MarketplaceID { get; set; }
        public string MarketplaceListingID { get; set; }
        public int CategoryID { get; set; }
        public int MarketplaceSKUTypeID { get; set; }
        public string MarketplaceSKU { get; set; }
        public string Condition { get; set; }
        public string ListingURL { get; set; }
        public bool IsListingOwner { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<MarketPlaceAttribute> MarketPlaceAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketplaceCompatibleSKU> MarketplaceCompatibleSKUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketplaceListingDetail> MarketplaceListingDetails { get; set; }
        public virtual Marketplace Marketplace { get; set; }
        public virtual MarketplaceSKUType MarketplaceSKUType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketplacePrice> MarketplacePrices { get; set; }
    }
}
