//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketplaceCompatibleSKU
    {
        public int MarketplaceCompatibleSKUID { get; set; }
        public int MarketplaceItemID { get; set; }
        public int PriorityLevel { get; set; }
        public string MITSKU1 { get; set; }
        public int QtyRequired1 { get; set; }
        public string MITSKU2 { get; set; }
        public Nullable<int> QtyRequired2 { get; set; }
        public string MITSKU3 { get; set; }
        public Nullable<int> QtyRequired3 { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual MarketplaceManagement MarketplaceManagement { get; set; }
    }
}
