//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketplaceListingDetail
    {
        public int MarketplaceListingDetailID { get; set; }
        public int MarketplaceItemID { get; set; }
        public string ChannelBrandOwner { get; set; }
        public string ChannelBrandName { get; set; }
        public string ChannelPartNumber { get; set; }
        public string ChannelProductTitle { get; set; }
    
        public virtual MarketplaceManagement MarketplaceManagement { get; set; }
    }
}
