//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketplacePrice
    {
        public int MarketplacePriceID { get; set; }
        public int MarketplaceItemID { get; set; }
        public decimal SellPrice { get; set; }
        public decimal FloorPrice { get; set; }
        public decimal CeilingPrice { get; set; }
        public Nullable<decimal> FixedPrice { get; set; }
        public bool IsFixedPrice { get; set; }
    
        public virtual MarketplaceManagement MarketplaceManagement { get; set; }
    }
}
