//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketplaceMerchantSKU
    {
        public int MerchantID { get; set; }
        public int CompanyID { get; set; }
        public string SKU { get; set; }
        public string ASIN { get; set; }
        public string MerchantSKU { get; set; }
        public int AccountID { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual MarketplaceAccount MarketplaceAccount { get; set; }
    }
}
