//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenCellDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpenCellDetail()
        {
            this.OpenCellDetailImages = new HashSet<OpenCellDetailImage>();
        }
    
        public int OpenCellDetailID { get; set; }
        public int OpenCellID { get; set; }
        public int CompanyID { get; set; }
        public string LicensePlateNumber { get; set; }
        public int PartID { get; set; }
        public string PartNumber { get; set; }
        public string PartVersion { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual OpenCellPart OpenCellPart { get; set; }
        public virtual OpenCellData OpenCellData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenCellDetailImage> OpenCellDetailImages { get; set; }
    }
}
