//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenCellData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpenCellData()
        {
            this.OpenCellDataImages = new HashSet<OpenCellDataImage>();
            this.OpenCellDetails = new HashSet<OpenCellDetail>();
        }
    
        public int OpenCellID { get; set; }
        public string LicensePlateNumber { get; set; }
        public int CompanyID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public string CountryOrigin { get; set; }
        public System.DateTime ManufactureDate { get; set; }
        public int ScreenSize { get; set; }
        public int TypeOfWork { get; set; }
        public string SKU { get; set; }
        public Nullable<int> BinMovementID { get; set; }
        public string OpenCellPartNumber { get; set; }
        public string OpenCellVersion { get; set; }
        public string OpenCellSerialNumber { get; set; }
        public string OpenCellCountryOrigin { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenCellDataImage> OpenCellDataImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenCellDetail> OpenCellDetails { get; set; }
    }
}
