//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenCellDataImage
    {
        public int ImageID { get; set; }
        public int CompanyID { get; set; }
        public int OpenCellID { get; set; }
        public string PhotoName { get; set; }
        public byte PhotoNumber { get; set; }
        public string PhotoWebURL { get; set; }
        public string PhotoLocalRoot { get; set; }
        public string OriginalPhotoName { get; set; }
        public string PhotoExtension { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        public virtual OpenCellData OpenCellData { get; set; }
    }
}
