//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.AssignmentPages = new HashSet<AssignmentPage>();
            this.LogPageHits = new HashSet<LogPageHit>();
            this.UserConfigurations = new HashSet<UserConfiguration>();
        }
    
        public int PageID { get; set; }
        public int CompanyID { get; set; }
        public string PageName { get; set; }
        public string NavigationURL { get; set; }
        public string PageTitle { get; set; }
        public string PageTitleMX { get; set; }
        public string PageDescription { get; set; }
        public string PageDescriptionMX { get; set; }
        public bool NeedTarget { get; set; }
        public string PageIcon { get; set; }
        public string PageColor { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentPage> AssignmentPages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPageHit> LogPageHits { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConfiguration> UserConfigurations { get; set; }
    }
}
