//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintingList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrintingList()
        {
            this.PrintingListDetails = new HashSet<PrintingListDetail>();
        }
    
        public int PrintingID { get; set; }
        public int CompanyID { get; set; }
        public int WorkOrderID { get; set; }
        public string WOType { get; set; }
        public int WorkOrderDetailID { get; set; }
        public string PrintedBy { get; set; }
        public System.DateTime PrintedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintingListDetail> PrintingListDetails { get; set; }
    }
}
