//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int ID { get; set; }
        public string SohnenLoadID { get; set; }
        public string Brand { get; set; }
        public string ScreenSize { get; set; }
        public string MFGSKU { get; set; }
        public string ItemDescription { get; set; }
        public int Qty { get; set; }
        public decimal EstimatedRetail { get; set; }
        public decimal Price { get; set; }
        public string BTSLoadID { get; set; }
        public System.DateTime LoadDate { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string BTSSKU { get; set; }
        public Nullable<int> BTSCategoryID { get; set; }
    }
}
