//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseDetail()
        {
            this.CostHistories = new HashSet<CostHistory>();
        }
    
        public int PurchaseDetailID { get; set; }
        public int PurchaseID { get; set; }
        public int CompanyID { get; set; }
        public string Brand { get; set; }
        public Nullable<int> ScreenSize { get; set; }
        public string MFGSKU { get; set; }
        public string ItemDescription { get; set; }
        public int Qty { get; set; }
        public decimal EstimatedRetail { get; set; }
        public decimal Price { get; set; }
        public string BTSSKU { get; set; }
        public int BTSCategoryID { get; set; }
        public bool isAddedManually { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostHistory> CostHistories { get; set; }
        public virtual Purchases1 Purchases1 { get; set; }
    }
}
