//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportFilterEmail
    {
        public int ReportFilterEmailID { get; set; }
        public int FilterID { get; set; }
        public int TriggerID { get; set; }
        public int FileTypeID { get; set; }
        public string Subject { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    }
}
