//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUData1
    {
        public int DataID { get; set; }
        public string SKU { get; set; }
        public int CompanyID { get; set; }
        public string Brand { get; set; }
        public string UPC { get; set; }
        public Nullable<decimal> UnitWeight { get; set; }
        public Nullable<decimal> UnitLength { get; set; }
        public Nullable<decimal> UnitWidth { get; set; }
        public Nullable<decimal> UnitHeight { get; set; }
        public string ManufacturerPN { get; set; }
        public string OriginManufacturer { get; set; }
        public string OriginalPartNumber { get; set; }
        public Nullable<int> ScreenSize { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
