//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUData
    {
        public int ID { get; set; }
        public string SKU { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public decimal EstimatedRetail { get; set; }
        public decimal AvgCost { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<decimal> PackageLength { get; set; }
        public Nullable<decimal> PackageWidth { get; set; }
        public Nullable<decimal> PackageHeight { get; set; }
        public Nullable<decimal> PackageWeightLBS { get; set; }
        public Nullable<decimal> SuggestedSalesPriceMXN { get; set; }
        public Nullable<System.DateTime> SuggestedSalesPriceMXNDate { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
