//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKURetailLinksDetail
    {
        public int SKURetailLinksDetailID { get; set; }
        public int SKURetailLinkID { get; set; }
        public string Store { get; set; }
        public string Link { get; set; }
        public string MITSKU { get; set; }
        public string Title { get; set; }
        public string PriceCurrency { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public bool Available { get; set; }
        public int Balance { get; set; }
        public bool Active { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> UpdateNow { get; set; }
        public string CreaterUser { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
