//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKURetailLink
    {
        public int SKURetailLinkID { get; set; }
        public string SKU { get; set; }
        public string Walmart { get; set; }
        public string Amazon { get; set; }
        public string Target { get; set; }
        public string Bestbuy { get; set; }
        public string AmazonMx { get; set; }
        public string MercadoLibreMx { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
