//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCode
    {
        public int SupplierCodeID { get; set; }
        public int SupplierID { get; set; }
        public int CompanyID { get; set; }
        public int CategoryID { get; set; }
        public string SupplierCode1 { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyCategory CompanyCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
