//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersForProductSKU
    {
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public int CompanyId { get; set; }
        public string ProductSKU { get; set; }
        public Nullable<decimal> SupplierCost { get; set; }
        public string SupplierSKU { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public System.DateTime AssignmentDate { get; set; }
    }
}
