//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.AssignedUsers = new HashSet<AssignedUser>();
            this.Attachments = new HashSet<Attachment>();
            this.Comments = new HashSet<Comment>();
            this.StatusChanges = new HashSet<StatusChanx>();
            this.TagByTickets = new HashSet<TagByTicket>();
        }
    
        public int Ticket_Id { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool Active { get; set; }
        public int Company_Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> RequiredByUser_Id { get; set; }
        public Nullable<int> RequiredByDepartament_Id { get; set; }
        public int ForApartment_Id { get; set; }
        public Nullable<int> Priority_Id { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public int Status_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedUser> AssignedUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusChanx> StatusChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagByTicket> TagByTickets { get; set; }
    }
}
