//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tier
    {
        public int ID { get; set; }
        public int TierID { get; set; }
        public string Category { get; set; }
        public string TierName { get; set; }
        public string TierDescription { get; set; }
        public string LastUpdateUser { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
