//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConfiguration
    {
        public int ConfigID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public int PageID { get; set; }
        public string UserID { get; set; }
        public int PageSequence { get; set; }
        public bool isActive { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual Company Company { get; set; }
    }
}
