//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_BulkMovementsList
    {
        public int Id { get; set; }
        public int Action { get; set; }
        public bool IsPrinted { get; set; }
        public string RegisteredDate { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public string CreatedBy { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseCode { get; set; }
    }
}
