//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InventoryDamagedTV
    {
        public string CategoryName { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string ProductSKU { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
