//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OpenCellChangeIncompatible
    {
        public int CompanyID { get; set; }
        public string OpenCellPartNumber { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string TVVersion { get; set; }
    }
}
