//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Purchases
    {
        public int CompanyID { get; set; }
        public int SupplierID { get; set; }
        public int PurchaseID { get; set; }
        public string LoadID { get; set; }
        public Nullable<bool> hasWorkPlan { get; set; }
        public string LoadDate { get; set; }
    }
}
