//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UrlByStores
    {
        public int SKURetailLinkID { get; set; }
        public string Amazon { get; set; }
        public string Target { get; set; }
        public string Bestbuy { get; set; }
        public string Walmart { get; set; }
        public string AmazonMx { get; set; }
        public string MercadoLibreMx { get; set; }
        public string SKU { get; set; }
        public int NeddUpdate_Walmart { get; set; }
        public int NeddUpdate_Target { get; set; }
        public int NeddUpdate_Bestbuy { get; set; }
        public int NeddUpdate_Amazon { get; set; }
        public int NeddUpdate_AmazonMx { get; set; }
        public int NeddUpdate_MercadoLibreMx { get; set; }
    }
}
