//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WorkPlanItemClassifications
    {
        public int ClassificationID { get; set; }
        public int CompanyID { get; set; }
        public string ClassificationName { get; set; }
        public string ClassificationCode { get; set; }
        public bool NeedPhoto { get; set; }
        public bool NeedComment { get; set; }
        public bool NeedAccessories { get; set; }
        public bool NeedPacking { get; set; }
    }
}
