//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseLocationsForCompany
    {
        public int Id { get; set; }
        public int Company_CompanyID { get; set; }
        public int Locations_LocationID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual WarehouseLocation WarehouseLocation { get; set; }
    }
}
