//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPlanTRGID
    {
        public int WPTRGID { get; set; }
        public int CompanyID { get; set; }
        public int WorkOrderID { get; set; }
        public string WOType { get; set; }
        public string TRGID { get; set; }
        public string UPC { get; set; }
        public string Model { get; set; }
        public bool isUsed { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RC { get; set; }
        public string BL { get; set; }
        public string PalletID { get; set; }
        public string SerialNumber { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public Nullable<int> Qty { get; set; }
        public string WalmartSLP { get; set; }
        public Nullable<decimal> EstimatedRetailPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> RevisedSalePrice { get; set; }
        public Nullable<decimal> ShippingDimensionD { get; set; }
        public Nullable<decimal> ShippingDimensionH { get; set; }
        public Nullable<decimal> ShippingDimensionW { get; set; }
        public Nullable<decimal> ProductWeight { get; set; }
    }
}
