//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPlanInspection
    {
        public int InspectionID { get; set; }
        public int CompanyID { get; set; }
        public string LicensePlateNumber { get; set; }
        public int WorkCenterID { get; set; }
        public string InspectionBy { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public Nullable<int> ClassificationID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual WorkPlan WorkPlan { get; set; }
    }
}
