//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.WorkOrderDetails = new HashSet<WorkOrderDetail>();
            this.WorkOrderHistories = new HashSet<WorkOrderHistory>();
        }
    
        public int WorkOrderID { get; set; }
        public string WOType { get; set; }
        public int CompanyID { get; set; }
        public int StatusID { get; set; }
        public string SourceOrderID { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<int> OrderTime { get; set; }
        public bool Printed { get; set; }
        public bool PriorityQueue { get; set; }
        public string Comment { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderDetail> WorkOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderHistory> WorkOrderHistories { get; set; }
        public virtual WorkOrderStatu WorkOrderStatu { get; set; }
    }
}
