//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPlanRepairHistory
    {
        public int HistoryID { get; set; }
        public int CompanyID { get; set; }
        public int RepairID { get; set; }
        public int StatusID { get; set; }
        public string Note { get; set; }
        public string RegisteredBy { get; set; }
        public System.DateTime RegisteredDate { get; set; }
    
        public virtual WorkPlanRepair WorkPlanRepair { get; set; }
    }
}
