//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPlanRepairAwaiting
    {
        public int AwaitingID { get; set; }
        public int CompanyID { get; set; }
        public int RepairID { get; set; }
        public int FailureID { get; set; }
        public string AwaitingBy { get; set; }
        public System.DateTime AwaitingDate { get; set; }
    
        public virtual WorkPlanRepairFailure WorkPlanRepairFailure { get; set; }
        public virtual WorkPlanRepair WorkPlanRepair { get; set; }
    }
}
