//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkPlan()
        {
            this.WorkPlanInspections = new HashSet<WorkPlanInspection>();
            this.WorkPlanItemAccessoriesCheckLists = new HashSet<WorkPlanItemAccessoriesCheckList>();
            this.WorkPlanItemPackings = new HashSet<WorkPlanItemPacking>();
            this.WorkPlanItemPhotoes = new HashSet<WorkPlanItemPhoto>();
            this.WorkPlanPackagingDetails = new HashSet<WorkPlanPackagingDetail>();
        }
    
        public string LicensePlateNumber { get; set; }
        public int WorkOrderDetailID { get; set; }
        public int CompanyID { get; set; }
        public string SKU { get; set; }
        public Nullable<int> ClassificationID { get; set; }
        public bool isNotReceived { get; set; }
        public string SerialNumber { get; set; }
        public string CommentID { get; set; }
        public string Comment { get; set; }
        public string UPC { get; set; }
        public bool isPrinted { get; set; }
        public Nullable<int> BinMovementID { get; set; }
        public string TRGID { get; set; }
        public string ModelVersion { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual WorkOrderDetail WorkOrderDetail { get; set; }
        public virtual WorkPlanItemClassification WorkPlanItemClassification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlanInspection> WorkPlanInspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlanItemAccessoriesCheckList> WorkPlanItemAccessoriesCheckLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlanItemPacking> WorkPlanItemPackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlanItemPhoto> WorkPlanItemPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlanPackagingDetail> WorkPlanPackagingDetails { get; set; }
    }
}
