//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrderDetail()
        {
            this.WorkPlans = new HashSet<WorkPlan>();
        }
    
        public int WorkOrderDetailID { get; set; }
        public int WorkOrderID { get; set; }
        public string WOType { get; set; }
        public int CompanyID { get; set; }
        public string SKU { get; set; }
        public int CategoryID { get; set; }
        public string MFRModel { get; set; }
        public int QtyOrdered { get; set; }
        public int QtyPacked { get; set; }
        public int QtyPrinted { get; set; }
        public bool isAddedManually { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyCategory CompanyCategory { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlan> WorkPlans { get; set; }
    }
}
