//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPlanItemClassification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkPlanItemClassification()
        {
            this.WorkCenterRoutings = new HashSet<WorkCenterRouting>();
            this.WorkPlans = new HashSet<WorkPlan>();
            this.WorkPlanAccessoriesClassifications = new HashSet<WorkPlanAccessoriesClassification>();
        }
    
        public int ClassificationID { get; set; }
        public int CompanyID { get; set; }
        public string ClassificationName { get; set; }
        public string ClassificationCode { get; set; }
        public bool NeedPhoto { get; set; }
        public bool NeedComment { get; set; }
        public bool NeedAccessories { get; set; }
        public bool NeedPacking { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ParentClassificationID { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkCenterRouting> WorkCenterRoutings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlan> WorkPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlanAccessoriesClassification> WorkPlanAccessoriesClassifications { get; set; }
    }
}
