//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderInspection
    {
        public int InspectionID { get; set; }
        public int WorkOrderID { get; set; }
        public string WOType { get; set; }
        public int CompanyID { get; set; }
        public string SKU { get; set; }
        public int InspectionAreaID { get; set; }
        public string InspectionBy { get; set; }
        public System.DateTime InspectionDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual WorkOrderInspectionArea WorkOrderInspectionArea { get; set; }
    }
}
