//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPlanItemAccessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkPlanItemAccessory()
        {
            this.WorkPlanAccessoriesClassifications = new HashSet<WorkPlanAccessoriesClassification>();
            this.WorkPlanItemAccessoriesCheckLists = new HashSet<WorkPlanItemAccessoriesCheckList>();
        }
    
        public int AccessoryID { get; set; }
        public int CategoryID { get; set; }
        public int CompanyID { get; set; }
        public string AccessoryName { get; set; }
        public bool isActive { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyCategory CompanyCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlanAccessoriesClassification> WorkPlanAccessoriesClassifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkPlanItemAccessoriesCheckList> WorkPlanItemAccessoriesCheckLists { get; set; }
    }
}
